HAM-Radio-ITU-Callsign-Prefix-Lookup-windows.zip:	HAM-Radio-ITU-Callsign-Prefix-Lookup/callsign-lookup.pl HAM-Radio-ITU-Callsign-Prefix-Lookup/ITU_prefix.txt
	zip -r HAM-Radio-ITU-Callsign-Prefix-Lookup-windows.zip HAM-Radio-ITU-Callsign-Prefix-Lookup/
